version: '3.8'

services:
  app:
    build: ./
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    extra_hosts:
      host.docker.internal: host-gateway
  nginx:
    container_name: webserver
    image: nginx:alpine
    ports:
      - ${APP_PORT:-80}:80
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME:-projeto_db}
      MYSQL_USER: ${MYSQL_DB_USER:-user_db}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/my.cnf

