services:
  php-api:
    build: ./
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      APP_ENV: ${APP_ENV}
      SESSION_HANDLER: redis
      SESSION_PATH: tcp://redis:${REDIS_PORT}?auth=${REDIS_PASSWORD}  
      SESSION_MAX_TIME_LIFE: 86400
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql:
          condition: service_healthy
      redis:
          condition: service_healthy
  nginx:
    container_name: webserver
    image: nginx:alpine
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-api
      - frontend
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    container_name: redis_server
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
  go-consumer-service:
    build: 
      context: ./consumer-service
      dockerfile: Dockerfile
    volumes:
      - ./consumer-service:/app
    

volumes:
  redis_data:
